/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Model.Dictionary;
import Model.HandleXMLFile;
import Model.Model_Button;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVEN
 */
public class AddNewWordForm extends javax.swing.JPanel {

    private int keyLanguage = 1; // 1 - Anh Viet ; 0 - Viet Anh 
    private int keyFavourite = 0; // 1 - true ; 0 - false
    private String textword;
    private String meaning;

    /**
     * Creates new form Form_1
     *
     */
    public AddNewWordForm() {
        initComponents();
        addBtn.setData(new Model_Button(new ImageIcon(getClass().getResource("/com/raven/icon/7.png")), "Thêm"));
        SwitchLanguage.setData(new Model_Button(new ImageIcon(getClass().getResource("/com/raven/icon/4.png")), "Anh - Việt"));
        favoriteWord.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new Components.Button();
        SwitchLanguage = new Components.Button();
        textWord = new Components.TextBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        meaningText = new javax.swing.JTextArea();
        titleSearch = new javax.swing.JLabel();
        favoriteWord = new javax.swing.JPanel();
        iconStar = new javax.swing.JLabel();
        titleSearch1 = new javax.swing.JLabel();

        addBtn.setColor1(new java.awt.Color(28, 181, 224));
        addBtn.setColor2(new java.awt.Color(0, 0, 120));
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBtnMouseEntered(evt);
            }
        });
        addBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addBtnKeyPressed(evt);
            }
        });

        SwitchLanguage.setColor1(new java.awt.Color(28, 181, 224));
        SwitchLanguage.setColor2(new java.awt.Color(0, 0, 120));
        SwitchLanguage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SwitchLanguageMouseClicked(evt);
            }
        });

        textWord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 181, 224), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(textWord, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SwitchLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SwitchLanguage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        meaningText.setColumns(20);
        meaningText.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        meaningText.setRows(5);
        jScrollPane1.setViewportView(meaningText);

        titleSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleSearch.setForeground(new java.awt.Color(16, 103, 158));
        titleSearch.setText("Nhập nghĩa của từ:");

        favoriteWord.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        favoriteWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                favoriteWordMouseClicked(evt);
            }
        });

        iconStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/star.png"))); // NOI18N

        titleSearch1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titleSearch1.setForeground(new java.awt.Color(16, 103, 158));
        titleSearch1.setText("Yêu thích");

        javax.swing.GroupLayout favoriteWordLayout = new javax.swing.GroupLayout(favoriteWord);
        favoriteWord.setLayout(favoriteWordLayout);
        favoriteWordLayout.setHorizontalGroup(
            favoriteWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(favoriteWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(favoriteWordLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(titleSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(iconStar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        favoriteWordLayout.setVerticalGroup(
            favoriteWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
            .addGroup(favoriteWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(favoriteWordLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(favoriteWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titleSearch1)
                        .addComponent(iconStar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(favoriteWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleSearch)
                    .addComponent(favoriteWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_addBtnMouseEntered

    private void SwitchLanguageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SwitchLanguageMouseClicked
        // TODO add your handling code here:
        if (keyLanguage == 1) {
            keyLanguage = 0;
            SwitchLanguage.setData(new Model_Button(new ImageIcon(getClass().getResource("/com/raven/icon/4.png")), "Việt - Anh"));
            //SearchText.setHintText("Nhập từ tiếng Việt");
        } else {
            keyLanguage = 1;
            SwitchLanguage.setData(new Model_Button(new ImageIcon(getClass().getResource("/com/raven/icon/4.png")), "Anh - Việt"));
            //SearchText.setHintText("Nhập từ tiếng Anh");

        }

    }//GEN-LAST:event_SwitchLanguageMouseClicked

    private int checkFavoriteWord(int keyL, String word) {
        if (keyL == 1) {
            if (Dictionary.listFavoriteWordEnglish.checkWord(word)) {
                return 1;
            }
            return 0;
        } else {
            if (Dictionary.listFavoriteWordVietnamese.checkWord(word)) {
                return 1;
            }
            return 0;
        }
    }

    private void addRecordFavorite(int keyL, String word, String meaning) {
        HandleXMLFile handleXMLFile = new HandleXMLFile();
        if (keyL == 1) {
            Dictionary.listFavoriteWordEnglish.addRecord(word, meaning);
            handleXMLFile.writeXMLFile("favoriteEnglish", "Data/favoriteEnglish.xml", Dictionary.listFavoriteWordEnglish, "word", "meaning");

        } else {
            Dictionary.listFavoriteWordVietnamese.addRecord(word, meaning);
            handleXMLFile.writeXMLFile("favoriteVietnamese", "Data/favoriteVietnamese.xml", Dictionary.listFavoriteWordVietnamese, "word", "meaning");

        }
    }

    private void removeRecordFavorite(int keyL, String word) {
        HandleXMLFile handleXMLFile = new HandleXMLFile();
        if (keyL == 1) {
            Dictionary.listFavoriteWordEnglish.removeRecord(word);
            handleXMLFile.writeXMLFile("favoriteEnglish", "Data/favoriteEnglish.xml", Dictionary.listFavoriteWordEnglish, "word", "meaning");

        } else {
            Dictionary.listFavoriteWordVietnamese.removeRecord(word);
            handleXMLFile.writeXMLFile("favoriteVietnamese", "Data/favoriteVietnamese.xml", Dictionary.listFavoriteWordVietnamese, "word", "meaning");

        }
    }

    public String handlingString(String str) {

        str = str.toLowerCase();
        str = str.trim();
        return str;
    }

    private void addRecordNewWord(int keyL, String word, String meaning) {
        HandleXMLFile handleXMLFile = new HandleXMLFile();
        if (keyL == 1) {
            Dictionary.listNewWordAnh_Viet.addRecord(word, meaning);
            handleXMLFile.writeXMLFile("newWordEng", "Data/newWordAnh_Viet.xml", Dictionary.listNewWordAnh_Viet, "word", "meaning");

        } else {
            Dictionary.listNewWordViet_Anh.addRecord(word, meaning);
            handleXMLFile.writeXMLFile("newWordVN", "Data/newWordViet_Anh.xml", Dictionary.listNewWordViet_Anh, "word", "meaning");

        }
    }

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        textword = textWord.getText();
        textword = handlingString(textword);
        meaning = meaningText.getText();

        System.out.println(textword + meaning);
        
        if (textword != null && !textword.trim().isEmpty() && meaning != null && !meaning.isEmpty()) {
            addRecordNewWord(keyLanguage, textword, meaning);
            JOptionPane.showMessageDialog(this, "Thêm từ mới thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");

        }


    }//GEN-LAST:event_addBtnMouseClicked

    private void setColorStar(int keyF) {
        if (keyF == 1) {
            iconStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/star_yellow.png")));

        } else {
            iconStar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/star.png")));

        }
    }

    private void favoriteWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_favoriteWordMouseClicked
        // TODO add your handling code here:
        if (keyFavourite == 0) {
            addRecordFavorite(keyLanguage, textword, meaning);
            keyFavourite = 1;
            setColorStar(keyFavourite);
            JOptionPane.showMessageDialog(this, "Thêm vào danh sách yêu thích thành công!");

        } else {
            removeRecordFavorite(keyLanguage, textword);
            keyFavourite = 0;
            setColorStar(keyFavourite);
            JOptionPane.showMessageDialog(this, "Đã xóa khỏi danh sách yêu thích !");
        }

    }//GEN-LAST:event_favoriteWordMouseClicked

    private void addBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addBtnKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_addBtnKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.Button SwitchLanguage;
    private Components.Button addBtn;
    private javax.swing.JPanel favoriteWord;
    private javax.swing.JLabel iconStar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea meaningText;
    private Components.TextBox textWord;
    private javax.swing.JLabel titleSearch;
    private javax.swing.JLabel titleSearch1;
    // End of variables declaration//GEN-END:variables
}
