/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Event.EventMenuSelected;
import Forms.AddNewWordForm;
import Forms.LookupForm;
import Forms.HandleNewWordForm;
import Forms.FavoriteListForm;
import Forms.LookupFrequencyStatisticsForm;
import Model.Dictionary;
import Model.HandleXMLFile;
import java.awt.Color;
import javax.swing.JComponent;

/**
 *
 * @author RAVEN
 */
public class Main extends javax.swing.JFrame{

    /**
     * Creates new form Main
     */
    Dictionary dictionary;
    HandleXMLFile handleXMLFile;
    private LookupForm lookupForm;
    private HandleNewWordForm handleNewWordForm;
    private FavoriteListForm favoriteListForm;
    private AddNewWordForm addNewWordForm;
    private LookupFrequencyStatisticsForm lookupFrequencyStatisticsForm;

    public Main() {
        init();
        initComponents();
        setBackground(new Color(0, 0, 0, 0));

        // set form
        lookupForm = new LookupForm(dictionary);
        handleNewWordForm = new HandleNewWordForm();
        favoriteListForm = new FavoriteListForm();
        addNewWordForm = new AddNewWordForm();
        lookupFrequencyStatisticsForm = new LookupFrequencyStatisticsForm();
        
        menu.initMoving(Main.this);
        menu.addEventMenuSelected(new EventMenuSelected() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    setForm(lookupForm);
                } else if (index == 1) {
                    setForm(addNewWordForm);
                } else if (index == 2) {
                    setForm(handleNewWordForm);
                } else if (index == 3) {
                    setForm(favoriteListForm);
                } else if(index == 4){
                    setForm(lookupFrequencyStatisticsForm);
                }
                else if (index == 6) {
                    System.exit(0);
                }
            }
        });
        //  set when system open start with home form
        setForm(new LookupForm(dictionary));
    }

    public void init() {
        dictionary = new Dictionary();
        handleXMLFile = new HandleXMLFile();
        dictionary.setAnh_Viet(handleXMLFile.readXMLFile("Data/Anh_Viet.xml", "word", "meaning"));
        dictionary.setViet_Anh(handleXMLFile.readXMLFile("Data/Viet_Anh.xml", "word", "meaning"));
        Dictionary.listFavoriteWordEnglish = (handleXMLFile.readXMLFile("Data/favoriteEnglish.xml", "word", "meaning"));
        Dictionary.listFavoriteWordVietnamese = (handleXMLFile.readXMLFile("Data/favoriteVietnamese.xml", "word", "meaning"));
        Dictionary.listNewWordAnh_Viet = (handleXMLFile.readXMLFile("Data/newWordAnh_Viet.xml", "word", "meaning"));
        Dictionary.listNewWordViet_Anh = (handleXMLFile.readXMLFile("Data/newWordViet_Anh.xml", "word", "meaning"));
        Dictionary.listSearch = handleXMLFile.readFileLookup("Data/listSearch.xml");
    }

    private void setForm(JComponent com) {
        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new Swing.PanelBorder();
        menu = new Components.Menu();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1100, 657));

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    private Components.Menu menu;
    private Swing.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
